repos:
  - repo: local
    hooks:
      - id: lint
        name: pre-commit lint
        language: system
        entry: pipenv run lint
        files: .*.py
        stages: [commit]
      - id: format
        name: pre-commit format
        language: system
        entry: pipenv run format
        files: .*.py
        stages: [commit]
      - id: test
        name: pre-push test
        language: system
        entry: pipenv run test
        files: .*.py
        stages: [push]
