repos:
  - repo: local
    hooks:
      - id: lint
        name: pre-commit lint
        language: system
        entry: pipenv run lint
        exclude: .pylintrc
        stages: [commit]
      - id: format
        name: pre-commit format
        language: system
        entry: pipenv run format
        exclude: .pylintrc
        stages: [commit]
      - id: test
        name: pre-push test
        language: system
        entry: pipenv run test
        files: .*.py
        stages: [push]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        name: commit-msg test
        stages: [commit-msg]
